### ISSUE TITLE
Proposal - update mime types file and use as default

### ISSUE THREAD

**Issue by camstuart** [raku-community-modules/raku-mime-types#11]
I'd like to propose that usage of this module be expanded to allow a "default" mime type file of the one that currently resides in the `doc/mime.types`

So, the usage will still allow an explicit mime file to be passed:

```raku
my $mime = MIME::Types.new('/etc/mime.types');
```

However, if the constructor is called without args, we use `doc/mime.types` as a default:

```raku
my $mime = MIME::Types.new; # uses: `doc/mime.types`
``` 

naturally, we would update `doc/mime.types` as part of the PR, which I would be happy to provide

**Comment by JJ** [comment]
Well, that file should probably be moved to a `resources` subdir, it will not get installed if it's outside that dir. Other than that, I guess it's OK.

**Comment by camstuart** [comment]
Good idea @JJ all done. I was fortunate to do my research first and discovered `resources` is actually a think in `META6.json` and then can be referenced with `%?RESOURCES<mime.types>` that's a very nice feature. Well done whoever implemented that!

**Comment by JJ** [comment]
That applies to pretty much everything in Raku :-)
