### ISSUE TITLE
Repair broken travis

### ISSUE THREAD

**Issue by camstuart** [raku-community-modules/raku-mime-types#13]
Seems like we just need a newer docker image, and to install dependencies with `zef` instead of panda

**Comment by camstuart** [comment]
According to this: https://docs.travis-ci.com/user/languages/community-supported-languages/

We nned 3 people from the community to maintain. I am happy to be one of those

**Comment by JJ** [comment]
@camstuart I'm sorry I missed this. I totally agree with you, but I don't think this is the place to say that. Not sure what's precisely the place either.
